preset:
  default:
    file: resume.json
    folder: ../../resume-json
    theme: shorter
  # pdf default
  pdf:
    theme: shorter
  # html default theme
  html:
    theme: elegant
  # simple theme, useful for html
  simple:
    theme: slick
  #
  cool:
    theme: timeline
  # elegant & minimal
  # with print function/css
  srt:
    theme: srt
